### ISSUE TITLE
[BUG] is:issue is:MORSECODE.FUN HACK MY COMPUTER AND THEN JUST SHUT DOWN HELP IS IT THE FBI OR CIA?????

### ISSUE THREAD

**Issue by Dart-Monkey-243** [juicyguyzer/morsecode.fun#1]
# Please complete all the sections, or else we will ignore it.

**Describe the bug**

**Debug Code shown in the error page (if shown)**
It should look something like: "EXCEPTION IN (?, LINE ? "???"): ?"

**To Reproduce**
Put here steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - OS [e.g. iOS]: 
 - Browser [e.g. chrome, safari]: 
 - Version [e.g. 22]: 

**Additional context**

**Comment by Igyeom** [comment]
None of the sections are completed. Closing issue.
