### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pengowray** [juicyguyzer/morsecode.fun#11]
# Please complete all the sections, or else we will ignore it.

**Describe the bug**
The keyer is cool and mostly works well, but if someone (like me) uses ctrl-tab to flip tabs, then the keyer gets jammed on. Tested in Firefox + Chrome / Windows.

**Debug Code shown in the error page (if shown)**

**To Reproduce**
1. go to https://indev.morsecode.fun/keyer-v2?lang=English
2. create a new tab and flip back and forth with ctrl-tab and/or ctrl-shift-tab.

also happens if you use shortcuts like Ctrl-L (to jump to address bar) and Ctrl-B to bring up bookmarks, and probably others too.

**Expected behavior**
Should do one or more of the following:

1. Deactivate the key's audio when it detects user has left the tab/page,
2. Use a different key to trigger the keyer other than Ctrl
3. Only allow the key to be pressed for a maximum of e.g. 1 second before silencing it

**Screenshots**

**Device (please complete the following information):**
 - OS: Win 10
 - Browser: Firefox 99 + also in Chrome Version 100.0.4896.127 (Official Build) (64-bit)

Cheers

**Comment by Igyeom** [comment]
Hey, I have noticed this problem too in my testing, but haven’t really thought much of it, thanks for pointing that out; I’ve been reminded and will probably fix it when I get the time to do so.

Many thanks!

**Comment by Igyeom** [comment]
Update: Now users may only trigger via the key [K].
I will mark this issue as resolved.
