### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Dart-Monkey-243** [juicyguyzer/morsecode.fun#2]
# Please complete all the sections, or else we will ignore it.

**Describe the bug**
When morse-coding(is that a word?) in the same minute in the morsecode.fun chat, it will bunch together and look very confusing 

**Debug Code shown in the error page (if shown)**
It should look something like: "EXCEPTION IN (?, LINE ? "???"): ?"

**To Reproduce**
Put here steps to reproduce the behavior.
Morse-code different messages in the same minute and the letters/numbers will bunch together
**Expected behavior**
It should add another line of text but showing the same time to make it easier to read for people

**Screenshots**

**Device (please complete the following information):**
 - OS [e.g. iOS]: ios,windows
 - Browser [e.g. chrome, safari]: chrome
 - Version [e.g. 22]: ipad, laptop

**Additional context**

**Comment by Igyeom** [comment]
Fixed. Try now; Closing issue.
