### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by Dart-Monkey-243** [juicyguyzer/morsecode.fun#3]
# Please complete all the sections, or else we will ignore it.

**Describe the bug**
When clicking/pressing on the "view profile" while logged in, it will appear a error page with "UnboundLocalError"

**Debug Code shown in the error page (if shown)**
It should look something like: "EXCEPTION IN (?, LINE ? "???"): ?"

**To Reproduce**
Log in with any account on indev.morsecode.fun and then click "view profile". It should show the error page.

**Expected behavior**
It should give the account holder their profile page.

**Screenshots**

**Device (please complete the following information):**
 - OS [e.g. iOS]: iOS, Windows
 - Browser [e.g. chrome, safari]: chrome
 - Version [e.g. 22]: indev

**Additional context**

**Comment by Dart-Monkey-243** [comment]
Unless its only me, and juicyguyzer just banned my account with is highly possible giving the fact that he is annoyed that i beat him in bongo for 3 times in a row while with god rng and luck but basically I'm just better lol.

**Comment by Dart-Monkey-243** [comment]
![3FA5BF15-4667-4208-ACB4-E18EAEAA7F94](https://user-images.githubusercontent.com/99074240/159205975-f7948ac7-9ebd-43c0-a43f-7091e509e5c5.png)

**Comment by Igyeom** [comment]
Fixed.
